### ISSUE TITLE
Family Symbol is Not Active

### ISSUE THREAD

**Issue by johnpierson** [woodsbagot/WombatDYN#1]
**Describe the bug**
When using the node, `FamilyInstance.ByPointHostTypeAndLevel` the error, "The symbol is not active" will show up. This only happens when there is a family loaded in the project that has not been used yet.

**To Reproduce**
1. In Revit, load a new family into the project (a simple door perhaps).
2. Select that family with the OOTB Family Types dropdown.
3. Attempt to place that door in any given wall.
4. You _should_ receive the "symbol is not active" error.

**Expected behavior**
That the node would activate the family symbol prior to placement.

**Screenshots**
There are several screenshots here, https://forum.dynamobim.com/t/wombatdynamo-the-symbol-is-not-active/14495/2

**Additional context**
The fix, http://thebuildingcoder.typepad.com/blog/2014/08/activate-your-family-symbol-before-using-it.html

**Comment by Dre-Tas** [comment]
Thanks John for reporting this. I'll take a look at it ASAP and release a bug fix soon.

**Comment by Dre-Tas** [comment]
@johnpierson It should be fixed in the new version just released. Let me know if there are issues 😉
