### ISSUE TITLE
Use of Wall.ByCurveAndLocation fails in Revit 2021 and 2022

### ISSUE THREAD

**Issue by boiiinng** [woodsbagot/WombatDYN#2]
**Describe the bug**
Wombat Node “Wall.ByCurveAndLocation” works in the attached Dynamo script in Revit 2020 to convert lines from a CAD link into Revit Walls, but it doesn't work in Revit 2021 or 2022. I get the following error:

Warning: Wall.ByCurveAndLocation operation failed.
Method not found: ‘Double Revit.GeometryConversion.UnitConverter.DynamoToHostFactor(Autodesk.Revit.DB.UnitType)’.

Note that the Wombat nodes Wall.ByCurveAndLevels & Wall.ByCurveAndHeight both work in all versions but they don’t allow wall alignment like the Location node does.

**To Reproduce**
[CADWalls.zip](https://github.com/woodsbagot/WombatDYN/files/6810032/CADWalls.zip)

**Expected behavior**
Script reads lines from a CAD link and uses them to generate curves which the Wombat Node uses to generate Walls.

**Desktop (please complete the following information):**
 - OS: Win 10 64 bit

**Comment by Dre-Tas** [comment]
Thanks for reporting @boiiinng !

We'll have a look as soon as possible

**Comment by Dre-Tas** [comment]
@boiiinng I quickly checked the attached zip folder but it only contains the Dynamo graph.

Could you please share any relevant file, including the CAD file?

**Comment by boiiinng** [comment]
I've included the Revit and CAD files I was using to test along with an updated graph which disconnects the layer options.  The 20 file works, the 21 doesn't.  Thanks.
[CADToWalls.zip](https://github.com/woodsbagot/WombatDYN/files/6823732/CADToWalls.zip)

**Comment by boiiinng** [comment]
Hi, just wondering if there's been any advancement into getting this node to work in newer versions?  Thanks.

**Comment by hepnerz** [comment]
Hi, I have been using Wall.ByCurveAndLocation in Revit 2021 (to great effect, it's really important on a number of routines in my office!), but I have got the same issue in Revit 2022. I suspect it might have something to do with the new ForgeTypeId change in the Revit's API?
I am really looking forward for a solution to this!

**Comment by Dre-Tas** [comment]
Thanks for reporting and for the suggestion!

Unfortunately I haven't had time to look at it yet but hopefully I should be able to give it a crack at some point this week.

I'll keep you posted

**Comment by Dre-Tas** [comment]
Hello everyone!

I just had a moment to check the issue, and yes it looks like the UnitType property doesn't exist anymore in Revit 2022!

Using ForgeTypeId could be a solution, but to do that I'd need to create another version of the Wombat package for Revit 2021 and above, while keeping and maintaining this version for Revit 2020 and below. It sounds absurd!

Unless you have a better solution, I'll need to park this for a moment until I have time to create a new version of the package.

Sorry guys!

**Comment by Dre-Tas** [comment]
I'm trying to get more clarity here as well: https://forum.dynamobim.com/t/revit-versions-in-ztn/42689/3
Just to keep you up to date

**Comment by Dre-Tas** [comment]
Fixed with version 2.3.5
Please find in the Dynamo Package Manager

**Comment by boiiinng** [comment]
> Fixed with version 2.3.5
> Please find in the Dynamo Package Manager

Can confirm it works in 21 & 22 now, thanks so much!!!

**Comment by hepnerz** [comment]
@Dre-Tas , sorry for taking so long to return - I can too confirm it's working like a charm in 21 & 22. Thank you for putting your time and effort on solving this!
